### ISSUE TITLE
Problem when unpacking item.msgbnd.dcx

### ISSUE THREAD

**Issue by ivanp93m** [ividyon/WitchyBND#15]
When I try to unpack item.msgbnd.dcx I have this error

D:\SteamLibrary\steamapps\common\Sekiro\KoR5\msg\zhocn\item.msgbnd.dcx: Unhandled exception: Please inform the author by providing the following text:
System.FormatException: Unknown DCX format.
   at SoulsFormats.DCX.Decompress(BinaryReaderEx br, Type& type) in ./SoulsFormats/Formats/DCX.cs:line 160
   at SoulsFormats.SFUtil.GetDecompressedBR(BinaryReaderEx br, Type& compression) in ./SoulsFormats/Util/SFUtil.cs:line 213
   at SoulsFormats.SoulsFile\`1.Is(String path) in ./SoulsFormats/Util/SoulsFile.cs:line 48
   at WitchyBND.Parsers.WPARAMBND3.Is(String path) in ./WitchyBND/Parsers/Binder/WPARAMBND3.cs:line 45
   at WitchyBND.CliModes.ParseMode.ParseFiles(List\`1 paths, Boolean recursive) in ./WitchyBND/CliModes/ParseMode.cs:line 44

**Comment by ividyon** [comment]
I cannot reproduce this with my Sekiro install. This "KoR5" folder sounds like some kind of mod, which could be doing small header edits to make tools like Witchy fail their extraction (by lightly corrupting the content). The vanilla zhocn msgbnd opens fine.

**Comment by ivanp93m** [comment]
Yes KoR5 its a mod, I can do something to fix it?
