### ISSUE TITLE
Unhandled exception after update to 2.14

### ISSUE THREAD

**Issue by ccmedavid** [ividyon/WitchyBND#33]
Unhandled exception:
System.UnauthorizedAccessException: Access to the path 'D:\Games\WitchyBND-v2.13.0.1\WitchyBND.exe.tmp' is denied.
   at System.IO.FileSystem.DeleteFile(String)
   at WitchyBND.Services.UpdateService.PostUpdateActions() in ./WitchyBND/Services/UpdateService.cs:line 210
   at WitchyBND.Program.<>c__DisplayClass5_0.<Main>b__1(CliOptions opt) in ./WitchyBND/Program.cs:line 154

PS: actually my stupid mistake never mind

**Comment by ccmedavid** [comment]
PS: actually my stupid mistake never mind
